#!/bin/sh
if [ -f "$AWS_ACCESS_KEY_ID_FILE" ]; then
  export AWS_ACCESS_KEY_ID=$(cat "$AWS_ACCESS_KEY_ID_FILE")
fi

if [ -f "$AWS_SECRET_ACCESS_KEY_FILE" ]; then
  export AWS_SECRET_ACCESS_KEY=$(cat "$AWS_SECRET_ACCESS_KEY_FILE")
fi

if [ -f "$PG_PASSWORD_FILE" ]; then
  export PG_PASSWORD=$(cat "$PG_PASSWORD_FILE")
fi

if [ -f "$WALE_S3_PREFIX_FILE" ]; then
  export WALE_S3_PREFIX=$(cat "$WALE_S3_PREFIX_FILE")
fi

exec "$@"
